// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const Format = {
  "SEMINARTALK": "SEMINARTALK",
  "EXPO": "EXPO",
  "PERFORMANCELIVESHOW": "PERFORMANCELIVESHOW",
  "CLASSTRAINING": "CLASSTRAINING",
  "NETWORKINGMEETING": "NETWORKINGMEETING",
  "SOCIALGATHERING": "SOCIALGATHERING",
  "TOURNAMENTCOMPETITION": "TOURNAMENTCOMPETITION",
  "TOURSWALKS": "TOURSWALKS",
  "CAMPTRIP": "CAMPTRIP",
  "EXHIBITION": "EXHIBITION"
};

const Category = {
  "MUSIC": "MUSIC",
  "FESTIVAL": "FESTIVAL",
  "PARTIESNIGHTLIFE": "PARTIESNIGHTLIFE",
  "SPORT": "SPORT",
  "KIDS": "KIDS",
  "HEALTH": "HEALTH",
  "TRIP": "TRIP",
  "WORKSHOP": "WORKSHOP",
  "COOKING": "COOKING",
  "BUSINESS": "BUSINESS",
  "ACTIVITY": "ACTIVITY",
  "CULTURE": "CULTURE",
  "COMEDY": "COMEDY",
  "CONCERT": "CONCERT",
  "PERFORMANCE": "PERFORMANCE",
  "FINEARTS": "FINEARTS",
  "THEATRE": "THEATRE",
  "LITERATURE": "LITERATURE",
  "PHOTOGRAPHY": "PHOTOGRAPHY",
  "TECHNOLOGY": "TECHNOLOGY",
  "OTHER": "OTHER",
  "UNTITLEDVALUE": "UNTITLEDVALUE"
};

const { Category, Images, Location, Event } = initSchema(schema);

export {
  Category,
  Images,
  Location,
  Event,
  Format,
  Category
};